workflows:
 release-ios-workflow:
    name: Release Prueba iOS Workflow
    instance_type: mac_mini
    triggering:
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    publishing:
      slack:
        channel: '#pruebacodemagic'
        notify_on_build_start: true
        notify:
          success: true
          failure: false
